### ISSUE TITLE
Bug: issues with RPC Schema for getStorageAt 

### ISSUE THREAD

**Issue by sambacha** [wevm/ox#33]
### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/ox/issues) for the bug I encountered.

### Ox Version

*

### Current Behavior

eth_getStorageAt has an optional param called 'requireCanonical'[^1]

### -32000 Error Types

eth_getStorageAt [ "0x<address>", { "blockHash": "0x<non-canonical-block-hash>", "requireCanonical": true } -> raise block-not-canonical error

### -32001 Error Types

eth_getStorageAt [ "0x<address>", { "blockHash": "0x<non-existent-block-hash>" } -> raise block-not-found error

eth_getStorageAt [ "0x<address>", { "blockHash": "0x<non-existent-block-hash>", "requireCanonical": false } -> raise block-not-found error

eth_getStorageAt [ "0x<address>", { "blockHash": "0x<non-existent-block-hash>", "requireCanonical": true } -> raise block-not-found error

```jsonc
  // eth_getStorageAt [ "0x<address>", { "blockHash": "0x<non-canonical-block-hash>", "requireCanonical": true } -> raise block-not-canonical error
  // https://github.com/ethereum/EIPs/blob/master/EIPS/eip-1474.md#:~:text=If%20the%20block%20is%20not%20found,found%20rather%20than%20block%2Dnot%2Dcanonical.
  '-32000': {
    'SERVER_ERROR': {
    standard: 'EIP-1474, EIP-1898',
    message: 'Server error: Invalid input, unable to locate canonical block',
    },
  },
  // eth_getStorageAt [ "0x<address>", { "blockHash": "0x<non-existent-block-hash>" } -> raise block-not-found error
  // eth_getStorageAt [ "0x<address>", { "blockHash": "0x<non-existent-block-hash>", "requireCanonical": false } -> raise block-not-found error
  // eth_getStorageAt [ "0x<address>", { "blockHash": "0x<non-existent-block-hash>", "requireCanonical": true } -> raise block-not-found error
  // https://github.com/ethereum/EIPs/blob/master/EIPS/eip-1474.md#:~:text=If%20the%20block%20is%20not%20found,found%20rather%20than%20block%2Dnot%2Dcanonical.
  '-32001': {
    standard: 'EIP-1474, EIP-1898',
    message: 'Server error: Requested resource, block,  not found.',
  },
```

[^1]: https://github.com/ethereum/EIPs/blob/master/EIPS/eip-1474.md#:~:text=If%20the%20block%20is%20not%20found,found%20rather%20than%20block%2Dnot%2Dcanonical

### Expected Behavior

Conform to the standard

### Anything else?

There are some more issues I saw in the RPC related stuff, some missing RPC methods related to transactions, etc. Can open additional issues.

**Comment by jxom** [comment]
EIP-1474 is Stagnant, and Ox follows the JSON-RPC Schema here: https://github.com/ethereum/execution-apis. The Execution APIs [do not list the `requireCanonical` flag](https://github.com/ethereum/execution-apis/blob/main/src/schemas/block.yaml#L128-L136) in their schema. Can take a look at adding it in if most execution clients support it.
